### ISSUE TITLE
Spack compiler installation issues for GCHP

### ISSUE THREAD

**Issue by tessac2** [geoschem/GCHP#320]
### Name and Institution (Required)

Name: Tessa Clarizio
Institution: University of Illinois Urbana Champaign

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x ] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x ] [Debugging GEOS-Chem and HEMCO `errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)`
- [ x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Hello! I am trying to install GCHP. I am stuck trying to get a more recent version of Spack downloaded (we currently have gcc 9.3.0 but need 10.2.0) I had been following the below link for Spack:

Link 1: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html 

However, when I follow these instructions, I get the following error at the "spack ${scope_args} install gcc " step: 
`==> Error: GCHP/spack/modules.yaml:5: Additional properties are not allowed ('default' was unexpected)
`

When I look at the specified yaml file, I see the following: 
"
DESCRIPTION   This file has recommended module settings for GCHP dependencies. It is meant to be used by including GCHP/spack as a custom scope for spack.

modules:
    default:
        tcl:
            naming_scheme: '{name}-{version}'
            intel-oneapi-compilers:
                environment:
                    set:
                        CC: 'icc'
                        CXX: 'icpc'
                        FC: 'ifort'

"

I am a bit confused because it seems to be specifying intel-oneapi compilers rather than gcc, but according to Issue #290 these instructions were meant to use gcc instead of the intel-oneapi compilers? 

Additionally, in Link 2 (below) it seems that intel-oneapi compilers are required to install? 
Link 2: https://gchp.readthedocs.io/en/stable/supplement/building-gchp-dependencies.html#install-spack-and-do-first-time-setup 

It seems like there is still a dependency on the intel compilers at this link as well: https://github.com/geoschem/GCHP/blob/main/spack/packages.yaml

I am a bit confused on how to proceed. Should I manually try installing gcc 10.2.0 (e.g. below)? Do I need to install the intel compilers too? 
`spack install gcc@10.2.0 %gcc@4.8.5 target=x86_64`

Thank you in advance for your advice and guidance!

**Comment by yantosca** [comment]
Thanks for writing @tessac2.  We have updated this for 14.2.0 but because it's not released yet the updated `modules.yaml` and `packages.yaml` aren't in the main branch yet.

Try the following
```console
cd GCHP
git checkout docs/dev
cd docs/source/geos-chem-shared-docs
git checkout main
git pull
```
Then the `docs/source/geos-chem-shared-docs/spack/modules.yaml` should look like this:
```yaml
# DESCRIPTION   This file has recommended module settings for
#               GEOS-Chem/GCHP/HEMCO GCHP dependencies. It is
#               meant to be used a custom scope for spack.

modules:
    default:
        tcl:
            naming_scheme: '{name}-{version}'
            gcc:
                environment:
                    set:
                        CC: 'gcc'
                        CXX: 'g++'
                        FC: 'gfortran'
```
and `packages.yaml` should look like this:
```yaml
# DESCRIPTION   This file has recommended package settings for
#               GEOS-Chem/GCHP/HEMCO dependencies. It is meant to be
#               as a custom scope for spack.
#
# HOW TO UPGRADE
#   1. Update package.<package-name>.version to the appropriate version number
#   2. Check for changes to the variants by running
#      `spack info <package-name>@<version>`. Only the
#      required extensions should be enabled.
#   3. Verify install spec with updated geoschem-deps/package.yaml by running 
#        spack -C ${model}/spack spec -I esmf^gcc^openmpi
#      where ${model} is one of "GCClassic", "GCHP", "HEMCO".
#      Check for duplicate installs (same package different hash)
#      and unnecessary dependencies.

packages:
  #
  # Preferred compiler
  #
  gcc:
    version: [10.2.0]
    variants: ^texinfo
  #
  # Core GEOS-Chem/GCHP/HEMCO dependencies
  #
  cmake:
    version: [3.22.2]
    variants: ~doc~ncurses+openssl+ownlibs~qt
    compiler: [gcc@10.2.0]
  esmf:
    version: [8.1.1]
    variants: ~pio~pnetcdf~xerces
    compiler: [gcc@10.2.0]    
  hdf5:
    version: [1.14.0]
    variants: ~doc~mpi+hl+pic+shared+threadsafe
    compiler: [gcc@10.2.0]
  netcdf-c:
    version: [4.8.1]
    variants: ^hdf5~doc~mpi+hl+pic+shared+threadsafe~dap~fsync~hdf4~jna~parallel-netcdf
    compiler: [gcc@10.2.0]    
  netcdf-fortran:
    version: [4.5.3]
    variants: ~doc+pic+shared
    compiler: [gcc@10.2.0]    
  openmpi:
    version: [4.1.0]
    variants: ~doc+auto+pmi
    compiler: [gcc@10.2.0]    
  #
  # Useful tools
  #
  cdo:
    version: [2.1.1]
    variants: ^hdf5~doc~mpi+hl+pic+shared+threadsafe
    compiler: [gcc@10.2.0]
  cgdb:
    version: [0.7.1]
    compiler: [gcc@10.2.0]
  environment-modules:
    version: [5.0.1]
    compiler: [gcc@10.2.0]
  flex:
    compiler: [gcc@10.2.0]    
  gdb:
    version: [9.2]
    variants: ~python~xz
    compiler: [gcc@10.2.0]
  nco:
    version: [5.1.4]
    variants: ^hdf5~doc~mpi+hl+pic+shared+threadsafe
    compiler: [gcc@10.2.0]
  #
  # Settings for all Spack-built packages
  #
  all:
    target: [x86_64]
    providers:
      mpi: [openmpi]
```
This has the reference to intel-oneapi-compilers removed, and should build GCC 10.2.0 etc.  Let me know if that works for you.
